[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate && pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && source ../venv/bin/activate && python -m uvicorn app:app --host 0.0.0.0 --port $PORT"
