[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && source ../venv/bin/activate && python -m uvicorn app:app --host 0.0.0.0 --port $PORT"
